'use strict';
(function(){
  const AS='./assets/authority/';
  const A={hero:AS+'authority.png',deal:AS+'deal_button.png',pressure:AS+'authority_pressure.png',folder:AS+'barrack_cases_icon.jfif',resolved:AS+'case_resolved.png',clash:AS+'clash.png',fight:AS+'fight.jfif',great:AS+'excellent.png'};
  const DEALS=[
    {title:'Место у окна',story:'Двое заключённых не поделили место в общей зоне. Оба считают, что правы.',img:'clash',choices:[['Поговорить с обоими',180,8,'clash'],['Разделить время поровну',220,5,'safe'],['Принять решение',260,12,'clash']]},
    {title:'Очередь за чаем',story:'В столовой начался спор: один человек пытается пройти без очереди. Люди ждут твоего решения.',img:'hero',choices:[['Вернуть очередь',170,6,'safe'],['Дать сторонам договориться',140,4,'clash'],['Решить самому',250,10,'clash']]},
    {title:'Пропавшая посылка',story:'Посылка пришла без подписи. Несколько человек уверяют, что она их. Нужно установить порядок.',img:'hero',choices:[['Проверить список',200,5,'safe'],['Разделить содержимое',230,7,'safe'],['Выслушать всех',190,9,'clash']]},
    {title:'Шум в бараке',story:'Двое спорят из-за шума после отбоя. Спор быстро собирает зрителей.',img:'clash',choices:[['Развести по местам',210,8,'safe'],['Поговорить один на один',190,6,'clash'],['Поставить точку',270,11,'clash']]},
    {title:'Долг за услугу',story:'Один человек требует вернуть долг, второй говорит, что срок ещё не вышел. Оба пришли к тебе.',img:'hero',choices:[['Дать срок',160,5,'safe'],['Разделить долг',230,8,'safe'],['Назначить решение',280,13,'clash']]},
    {title:'Кому достанется место',story:'Освободилась койка в более тихом углу барака. За неё уже спорят двое.',img:'clash',choices:[['Жребий',190,7,'safe'],['По очереди',180,5,'safe'],['Решить по ситуации',250,10,'clash']]}
  ];
  const SUPPORTS=[['Союзник','Старший заключённый предлагает поддержать твоё решение.',10,8],['Староста','Староста барака подтверждает твою версию событий.',14,6],['Свидетель','Свидетель рассказывает, как всё началось.',12,7]];
  let root=null,tapArea=null,originalTapHTML='',authorityActive=false,modalOpen=false,clashState=null,clashTimer=null,oppTimer=null;
  const $=id=>document.getElementById(id);
  const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fmt=n=>{n=Math.floor(Number(n)||0);return n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':String(n)};
  const state=()=>window.getGameState?window.getGameState():null;
  function img(name,cls){return '<img class="authority-img '+(cls||'')+'" src="'+encodeURI(A[name])+'" draggable="false" alt="">'}
  function openAuthorityModal(html,locked){const overlay=$('modal-overlay'),modal=$('modal'),content=$('modal-content');if(!overlay||!modal||!content)return;modal.classList.add('authority-modal');overlay.classList.remove('hidden');overlay.dataset.locked=locked?'1':'0';content.innerHTML=html;modalOpen=true}
  function closeAuthorityModal(){stopClash();const overlay=$('modal-overlay'),modal=$('modal');if(overlay)overlay.classList.add('hidden');if(overlay)overlay.dataset.locked='0';if(modal)modal.classList.remove('authority-modal');modalOpen=false}
  function reward(influence,respect,bonus){const s=state();if(!s)return;s.points=(Number(s.points)||0)+influence;s.cigarettes=(Number(s.cigarettes)||0)+Math.max(0,bonus||0);s.respect=(Number(s.respect)||0)+Math.max(0,respect||0);s.tasks=s.tasks||{};s.tasks.earned=(Number(s.tasks.earned)||0)+Math.max(0,bonus||0);s.tasks.authorityDeals=(Number(s.tasks.authorityDeals)||0)+1;try{if(typeof window.checkTasks==='function')window.checkTasks();s.saveUpdatedAt=Date.now();localStorage.setItem('avtoritet_save_v2',JSON.stringify(s))}catch(e){}const p=$('points'),r=$('respect-stat'),c=$('cigarettes');if(p)p.textContent=fmt(s.points);if(r)r.textContent=fmt(s.respect);if(c)c.textContent=fmt(s.cigarettes)}
  function setMessage(text){const e=$('event-message');if(!e)return;e.textContent=text;e.classList.remove('show');void e.offsetWidth;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
  function spendEnergy(amount){const s=state();amount=Math.max(0,Math.floor(amount||0));if(!s)return false;if(typeof s.energy!=='number')s.energy=0;if(s.energy<amount){setMessage('⚡ Не хватает энергии. Нужно '+amount+'.');return false}s.energy-=amount;if(typeof s.lastEnergyTime!=='number')s.lastEnergyTime=Date.now();s.saveUpdatedAt=Date.now();const e=$('energy');if(e)e.textContent=Math.floor(s.energy);try{localStorage.setItem('avtoritet_save_v2',JSON.stringify(s))}catch(err){}return true}
  function renderAuthority(){const s=state();if(!s||Number(s.points)<40000||s.currentObject!==4||s.jailed){deactivate();return}if(authorityActive)return;authorityActive=true;root.classList.add('authority-mode');root.classList.remove('game-booting');tapArea.classList.add('authority-tap-area');tapArea.innerHTML='<div class="authority-screen"><div class="authority-hero">'+img('hero','authority-hero-bg')+'<div class="authority-shade"></div><div class="authority-context"><span>📋 ДЕЛА БАРАКА</span><b>Твой голос имеет вес</b></div><div class="authority-influence"><span>🧠 ВЛИЯНИЕ</span><b id="authority-influence-value">'+fmt(s.points)+'</b></div><div class="authority-action-wrap"><button type="button" class="authority-desk-hotspot" data-authority-action="folder" aria-label="Папки с делами"></button></div></div><div class="authority-strip"><div><small>ЧЕФИР</small><b>🍵 '+fmt(s.cigarettes)+'</b></div><div><small>УВАЖЕНИЕ</small><b>🧠 '+fmt(s.respect)+'</b></div><div><small>СИЛА</small><b>💪 '+fmt(s.power)+'</b></div></div><div class="authority-mini-row"><div class="authority-mini-card"><b>📋 Дело барака</b><span>Случайная ситуация и выбор решения.</span></div><div class="authority-mini-card"><b>⚡ Стычка</b><span>Если спор не решить словами — начинается проверка реакции.</span></div></div></div>'}
  function deactivate(){
    if(!authorityActive)return;
    stopClash();
    authorityActive=false;
    root.classList.remove('authority-mode');
    tapArea.classList.remove('authority-tap-area');
    tapArea.innerHTML=originalTapHTML;
    // Restore object visuals after DOM rewrite
    if(typeof window.refreshObjectVisuals==='function'){
      // microtask so the restored nodes are in the document
      queueMicrotask(function(){window.refreshObjectVisuals();});
    }
  }
  function startDeal(free){if(modalOpen)return;const s=state();if(!s||Number(s.points)<40000||s.currentObject!==4||s.jailed)return;if(!free&&!spendEnergy(3))return;const d=DEALS[Math.floor(Math.random()*DEALS.length)];const support=Math.random()<.28?SUPPORTS[Math.floor(Math.random()*SUPPORTS.length)]:null;openAuthorityModal('<div class="authority-deal-window"><div class="authority-modal-head"><span class="authority-modal-icon">📋</span><div><small>ДЕЛО БАРАКА</small><h2>'+esc(d.title)+'</h2></div></div><div class="authority-deal-art">'+img(d.img,'authority-deal-art-img')+'</div><p class="authority-story">'+esc(d.story)+'</p>'+(support?'<div class="authority-support">🤝 <b>'+esc(support[0])+':</b> '+esc(support[1])+' <strong>+'+support[2]+' влияние</strong></div>':'')+'<div class="authority-choice-title">КАК ПОСТУПИТЬ?</div><div class="authority-choices">'+d.choices.map((c,i)=>'<button type="button" class="authority-choice" data-choice="'+i+'"><span>'+['💬','⚖️','👑'][i]+'</span><b>'+esc(c[0])+'</b><small>+'+c[1]+' влияние · шанс спокойно решить '+(100-c[2])+'%</small></button>').join('')+'</div></div>',true);document.querySelectorAll('.authority-choice').forEach(b=>b.addEventListener('click',()=>resolveDeal(d,Number(b.dataset.choice),support)))}
  function resolveDeal(d,index,support){if(!modalOpen)return;const c=d.choices[index];if(!c)return;const success=Math.random()>=c[2]/100;if(support&&success)reward(support[2],1,0);if(success&&(c[3]==='safe'||Math.random()<.35)){reward(c[1],1,Math.floor(c[1]/8));showResult(true,c[1]+(support?support[2]:0),1,'Конфликт улажен. В бараке снова порядок.');return}reward(Math.floor(c[1]*.2),0,0);startClash({title:d.title,base:c[1],respect:2+(index===2?1:0),image:Math.random()<.2?'fight':'clash'})}
  function startClash(info){stopClash();const target=12+Math.floor(Math.random()*5),time=4200;clashState={...info,target,player:0,opponent:0,started:performance.now(),time};openAuthorityModal('<div class="authority-clash-window"><div class="authority-modal-head"><span class="authority-modal-icon">⚡</span><div><small>СТЫЧКА</small><h2>Кто быстрее?</h2></div></div><div class="authority-clash-art">'+img(info.image,'authority-clash-img')+'<div class="authority-art-vignette"></div></div><p class="authority-story">Спор перешёл в короткую проверку реакции. Нажимай быстро и набери <b>'+target+'</b> очков раньше оппонента.</p><div class="clash-score-row"><div><small>ТВОЁ ВЛИЯНИЕ</small><b id="authority-player-score">0 / '+target+'</b></div><div><small>ОППОНЕНТ</small><b id="authority-opponent-score">0 / '+target+'</b></div></div><div class="clash-bars"><div class="clash-bar"><span id="authority-player-bar"></span></div><div class="clash-bar opponent"><span id="authority-opponent-bar"></span></div></div><button type="button" class="authority-pressure-btn" id="authority-pressure">'+img('pressure','authority-pressure-img')+'</button><div class="authority-clash-timer" id="authority-clash-timer">4.2</div><div class="authority-clash-note">Нажимай по кнопке как можно быстрее</div></div>',true);oppTimer=setInterval(()=>{if(!clashState)return;clashState.opponent+=1+(Math.random()<.2?1:0);updateClash();checkClashEnd()},330);clashTimer=setInterval(()=>{if(!clashState)return;const left=Math.max(0,clashState.time-(performance.now()-clashState.started));const el=$('authority-clash-timer');if(el)el.textContent=(left/1000).toFixed(1);if(left<=0)finishClash(false)},50)}
  function clashTap(e){if(e&&e.preventDefault)e.preventDefault();if(!clashState)return;clashState.player+=1+(Math.random()<.16?1:0);updateClash();checkClashEnd()}
  function updateClash(){if(!clashState)return;const p=$('authority-player-score'),o=$('authority-opponent-score'),pb=$('authority-player-bar'),ob=$('authority-opponent-bar');if(p)p.textContent=clashState.player+' / '+clashState.target;if(o)o.textContent=clashState.opponent+' / '+clashState.target;if(pb)pb.style.width=Math.min(100,clashState.player/clashState.target*100)+'%';if(ob)ob.style.width=Math.min(100,clashState.opponent/clashState.target*100)+'%'}
  function checkClashEnd(){if(!clashState)return;if(clashState.player>=clashState.target){finishClash(true);return}if(clashState.opponent>=clashState.target)finishClash(false)}
  function finishClash(win){if(!clashState)return;const info=clashState;stopClash();if(win){const bonus=info.base+60;reward(bonus,info.respect,Math.floor(bonus/7));showResult(true,bonus,info.respect,'Ты не дал спору разгореться. Твоё решение приняли.')}else{const loss=Math.max(25,Math.floor(info.base*.35));const s=state();if(s){s.points=Math.max(0,s.points-loss);s.respect=Math.max(0,(s.respect||0)-1);try{s.saveUpdatedAt=Date.now();localStorage.setItem('avtoritet_save_v2',JSON.stringify(s))}catch(e){}}showResult(false,-loss,0,'Оппонент оказался быстрее. Часть влияния потеряна.')}}
  function stopClash(){if(clashTimer){clearInterval(clashTimer);clashTimer=null}if(oppTimer){clearInterval(oppTimer);oppTimer=null}clashState=null}
  function showResult(win,influence,respect,text){openAuthorityModal('<div class="authority-result '+(win?'success':'fail')+'"><div class="authority-result-art">'+img(win?'resolved':'clash','authority-result-img')+'<div class="authority-result-overlay"></div><div class="authority-result-title">'+(win?'✓ ДЕЛО РЕШЕНО':'⚠ ДЕЛО НЕ РЕШЕНО')+'</div></div><p>'+esc(text)+'</p><div class="authority-result-reward"><span>👑 '+(influence>=0?'+':'−')+fmt(Math.abs(influence))+' влияние</span>'+(respect?'<span>🧠 +'+respect+' уважение</span>':'')+'</div><button type="button" class="authority-great-btn" id="authority-great">'+img('great','authority-great-img')+'</button></div>',false)}
  function handleAuthorityButton(e){const target=e.target.closest('.authority-deal-btn,.authority-pressure-btn,.authority-great-btn');if(!target)return;const s=state();if(!s||Number(s.points)<40000||s.currentObject!==4||s.jailed)return;e.preventDefault();e.stopImmediatePropagation();if(target.classList.contains('authority-deal-btn'))startDeal();else if(target.classList.contains('authority-pressure-btn'))clashTap(e);else{closeAuthorityModal();setMessage('📋 Дело закрыто. Авторитет растёт.')}}
  function capture(e){const s=state();if(!s||Number(s.points)<40000||s.currentObject!==4||s.jailed)return;const hotspot=e.target.closest('.authority-desk-hotspot');if(hotspot)return;const target=e.target.closest('.authority-deal-btn,.authority-pressure-btn,.authority-great-btn');if(target){e.preventDefault();e.stopImmediatePropagation();if(target.classList.contains('authority-deal-btn'))startDeal();else if(target.classList.contains('authority-pressure-btn'))clashTap(e);else{closeAuthorityModal();setMessage('📋 Дело закрыто. Авторитет растёт.')}return}e.stopImmediatePropagation();e.preventDefault()}
  function sync(){const s=state();if(!s||Number(s.points)<40000||s.currentObject!==4||s.jailed){deactivate();return}if(!authorityActive)renderAuthority()}
  window.startAuthorityDeal=function(){startDeal(true)};
  function init(){root=$('game-container');tapArea=$('tap-area');if(!root||!tapArea)return;originalTapHTML=tapArea.innerHTML;tapArea.addEventListener('pointerdown',capture,true);document.addEventListener('pointerdown',handleAuthorityButton,true);setInterval(sync,350);sync();const close=$('modal-close');if(close)close.addEventListener('click',()=>{if(modalOpen&&$('modal-overlay')?.dataset.locked!=='1')closeAuthorityModal()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
