/* АВТОРИТЕТ 2.0 — стабильная версия */
'use strict';
const N=['Кирпич','Шайба','Бугор','Хмурый','Косой','Гвоздь','Топор','Серый','Лысый','Крест','Малой','Брат','Штиль','Волк','Кабан','Ёжик','Пупс','Змей','Тигр','Кощей','Батя','Шустрый','Немой','Гроза'];
const R=[['Салага',0],['Пацан',100],['Блатной',500],['Смотрящий',2000],['Авторитет',8000],['Вор в законе',25000]];
const O=[['Груша','🥊',1,0],['Сокамерник','👊',1.3,150],['Отжимания','💪',1.6,400],['Тренажёр','🏋️',2.2,1500],['Авторитет','👑',3.2,6000]];
const EVENTS=[['Шмон!','Надзиратели ворвались в камеру. Что делаешь?',[['Спрятать папиросы',.55,40,15],['Стоять спокойно',0,10,5],['Сделать вид, что спишь',.25,5,8]]],['Малява','Тебе передали маляву. Что в ней?',[['Прочитать сразу',.4,30,20],['Спрятать до завтра',.15,15,10],['Выбросить',0,0,3]]],['Посылка','Пришла посылка, но непонятно чья.',[['Забрать себе',.6,60,10],['Отдать смотрящему',0,0,20],['Оставить',.1,0,5]]]];
const FUN=['Надзиратель идёт... сделай умный вид.','Сегодня без шмона. Чудо.','Шайба сказал, что ты нормальный пацан.','Кто-то опять спиздил папиросы. Классика.','В столовой сегодня мясо. Или что-то похожее.','Сегодня раздача посылок. Надежда умирает последней.'];
const NPCS={
 шайба:{name:'Шайба',icon:'🧢',desc:'торговец',action:'Попросить скидку',run(){const gain=25+s.prestige*5;s.cigarettes+=gain;s.respect+=1;msg('🧢 Шайба помог: +'+gain+' 🚬 и +1 🧠')}},
 бугор:{name:'Бугор',icon:'💪',desc:'даёт задания',action:'Потренироваться',run(){if(s.energy<10){msg('⚡ Бугор: сначала восстанови хотя бы 10 энергии');return}s.energy-=10;s.power++;s.respect+=2;s.points+=15;msg('💪 Бугор потренировал тебя: +1 💪 +2 🧠 +15 ⭐')}},
 косой:{name:'Косой',icon:'😏',desc:'рискованные сделки',action:'Рискнуть',run(){const win=Math.random()<.55;if(win){s.cigarettes+=100;s.points+=40;msg('😏 Косой: сделка удалась! +100 🚬 +40 ⭐')}else{s.cigarettes=Math.max(0,s.cigarettes-60);s.points=Math.max(0,s.points-20);msg('😏 Косой: сделка провалилась. -60 🚬 -20 ⭐')}}},
 смотрящий:{name:'Смотрящий',icon:'👑',desc:'следит за продвижением',action:'Получить совет',run(){const r=rank();msg('👑 Смотрящий: твой текущий уровень — «'+r[0]+'». Следующая цель: '+fmt((R.find(x=>x[1]>s.points)||R[R.length-1])[1])+' ⭐')}}
};
let s={cigarettes:0,points:0,energy:250,maxEnergy:250,power:1,critChance:.05,respect:0,wealth:0,nickname:'',currentObject:0,prestige:0,upgrades:{power:0,crit:0,energyMax:0},boosters:{double:0},tasks:{taps:0,crit:0,events:0,earned:0},completed:{},lastEnergyTime:Date.now(),lastChoiceEvent:0,totalTaps:0};
let started=false, messageQueue=[], messageBusy=false, activeEvent=false;
const $=id=>document.getElementById(id);
function save(){try{s.lastEnergyTime=Date.now();localStorage.setItem('avtoritet_save_v2',JSON.stringify(s))}catch(e){}}
function highestUnlocked(){let i=0;for(let j=0;j<O.length;j++)if(s.points>=O[j][3])i=j;return i}
function syncObject(showMessage){const max=highestUnlocked();if(s.currentObject>max)s.currentObject=max;if(s.currentObject===0&&max>0){s.currentObject=max;if(showMessage)msg('🔓 Открыт новый объект: '+O[max][0])}}
function load(){try{const raw=localStorage.getItem('avtoritet_save_v2');if(raw){const d=JSON.parse(raw);if(d&&typeof d==='object')s={...s,...d,upgrades:{...s.upgrades,...(d.upgrades||{})},tasks:{...s.tasks,...(d.tasks||{})},boosters:{...s.boosters,...(d.boosters||{})}}}}catch(e){}if(!s.nickname)s.nickname=N[Math.floor(Math.random()*N.length)];if(!Number.isFinite(s.energy))s.energy=250;if(!Number.isFinite(s.maxEnergy))s.maxEnergy=250;if(!Number.isFinite(s.lastEnergyTime))s.lastEnergyTime=Date.now();s.energy=Math.min(s.maxEnergy,s.energy+Math.floor(Math.max(0,Date.now()-s.lastEnergyTime)/30000));syncObject(false)}
function fmt(n){n=Math.floor(Number(n)||0);return n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':String(n)}
function rank(){let r=R[0];for(const x of R)if(s.points>=x[1])r=x;return r}
function ui(){const ids=['cigarettes','points','energy','max-energy','nickname','rank','power-stat','respect-stat','wealth-stat','object-emoji','object-name'];if(ids.some(id=>!$(id)))return;$('cigarettes').textContent=fmt(s.cigarettes);$('points').textContent=fmt(s.points);$('energy').textContent=Math.floor(s.energy);$('max-energy').textContent=s.maxEnergy;$('nickname').textContent=s.nickname;$('rank').textContent=rank()[0];$('power-stat').textContent=s.power;$('respect-stat').textContent=s.respect;$('wealth-stat').textContent=s.wealth;const o=O[s.currentObject]||O[0];$('object-emoji').textContent=o[1];$('object-name').textContent=o[0]}
function msg(x){messageQueue.push(String(x));processMessages()}
function processMessages(){if(messageBusy||!messageQueue.length)return;const e=$('event-message');if(!e){messageQueue=[];return}messageBusy=true;e.textContent=messageQueue.shift();e.classList.add('show');setTimeout(()=>{e.classList.remove('show');setTimeout(()=>{messageBusy=false;processMessages()},250)},4200)}
function feedback(e,n,c){const x=$('tap-feedback');if(!x)return;x.textContent=(c?'КРИТ! ':'+')+n;x.style.left=(e&&e.clientX||150)+'px';x.style.top=(e&&e.clientY||250)+'px';x.classList.remove('show');void x.offsetWidth;x.classList.add('show')}
function tap(e){if(activeEvent)return;if(s.energy<1){msg('⚡ Энергия закончилась. Отдохни или используй бонус.');return}e&&e.preventDefault&&e.preventDefault();s.energy--;s.totalTaps++;s.tasks.taps++;let g=s.power*O[s.currentObject][2];const c=Math.random()<s.critChance;if(c){g*=2;s.tasks.crit++}if(s.boosters.double>0){g*=2;s.boosters.double--}s.cigarettes+=g;s.tasks.earned+=g;s.points+=g*.8;const t=$('tap-object');if(t){t.classList.remove('punch');void t.offsetWidth;t.classList.add('punch')}feedback(e,Math.floor(g),c);const old=s.currentObject;syncObject(true);if(old!==s.currentObject)ui();if(Math.random()<.025)msg(FUN[Math.floor(Math.random()*FUN.length)]);if(Math.random()<.012&&s.points-s.lastChoiceEvent>30)openEvent();tasksCheck();ui();save()}
function openModal(h,locked=false){const c=$('modal-content'),o=$('modal-overlay');if(!c||!o)return;c.innerHTML=h;o.classList.remove('hidden');o.dataset.locked=locked?'1':'0';}
function closeModal(){const o=$('modal-overlay');if(!o)return;if(o.dataset.locked==='1')return;o.classList.add('hidden')}
function finishEvent(){activeEvent=false;const o=$('modal-overlay');if(o)o.dataset.locked='0';closeModal();tasksCheck();ui();save()}
function openEvent(){if(activeEvent)return;activeEvent=true;const v=EVENTS[Math.floor(Math.random()*EVENTS.length)];let h='<h2>⚠️ '+v[0]+'</h2><p>'+v[1]+'</p><p><b>Выбери один вариант:</b></p><div class="choices">';v[2].forEach((c,i)=>h+='<button type="button" class="choice" data-i="'+i+'">'+c[0]+'</button>');openModal(h+'</div>',true);document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>{if(!activeEvent)return;const c=v[2][Number(b.dataset.i)];s.tasks.events++;if(Math.random()>c[1]){s.cigarettes+=c[2];s.tasks.earned+=c[2];s.points+=c[3];s.respect+=Math.floor(c[3]/5);msg('Удачно! +'+c[2]+' 🚬 +'+c[3]+' ⭐')}else{s.points=Math.max(0,s.points-Math.max(3,Math.ceil(c[3]*1.5)));msg('Не повезло. Авторитет пострадал.')}finishEvent()}))}
function objectMenu(){let max=highestUnlocked(),h='<h2>🥊 Объекты</h2><p>Каждый новый объект увеличивает доход за тап.</p><div class="shop-grid">';O.forEach((o,i)=>{const unlocked=i<=max;h+='<button type="button" data-o="'+i+'" '+(unlocked?'':'disabled')+'>'+o[1]+' '+o[0]+'<br>×'+o[2]+' · '+(unlocked?'Открыт':'🔒 '+fmt(o[3])+' ⭐')+(i===s.currentObject?' · ВЫБРАН':'')+'</button>'});openModal(h+'</div>');document.querySelectorAll('[data-o]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.o);if(i>highestUnlocked())return;s.currentObject=i;ui();save();objectMenu()}))}
function shop(){openModal('<h2>🛒 Магазин</h2><div class="shop-grid"><button type="button" data-b="p">💪 Сила<br>Цена '+(100+s.upgrades.power*250)+'</button><button type="button" data-b="c">🎯 Крит<br>Цена '+(300+s.upgrades.crit*500)+'</button><button type="button" data-b="e">⚡ Энергия<br>Цена '+(400+s.upgrades.energyMax*700)+'</button><button type="button" data-b="d">🔥 ×2 на 100 тапов<br>Цена 500</button></div><button type="button" id="objects-btn" style="width:100%;margin-top:10px">🥊 Выбрать объект</button>');document.querySelectorAll('[data-b]').forEach(b=>b.addEventListener('click',()=>buy(b.dataset.b)));const ob=$('objects-btn');if(ob)ob.addEventListener('click',objectMenu)}
function buy(k){const p=k==='p'?100+s.upgrades.power*250:k==='c'?300+s.upgrades.crit*500:k==='e'?400+s.upgrades.energyMax*700:500;if(s.cigarettes<p){msg('Не хватает сигарет');return}s.cigarettes-=p;if(k==='p'){s.power++;s.upgrades.power++}else if(k==='c'){s.critChance=Math.min(.5,s.critChance+.02);s.upgrades.crit++}else if(k==='e'){s.maxEnergy+=25;s.energy+=25;s.upgrades.energyMax++}else{s.boosters.double=(s.boosters.double||0)+100;msg('🔥 Бустер: следующие 100 тапов ×2')}ui();save();shop()}
function taskMenu(){const q=[['taps','500 тапов',500,100],['crit','20 критов',20,150],['events','3 события',3,200],['earned','1000 сигарет',1000,250]];let h='<h2>🎯 Задания</h2>';q.forEach(x=>h+='<p>'+(s.completed[x[0]]?'✅':'⬜')+' '+x[1]+' — '+x[3]+' 🚬</p>');openModal(h)}
function tasksCheck(){[['taps',500,100],['crit',20,150],['events',3,200],['earned',1000,250]].forEach(x=>{if(!s.completed[x[0]]&&s.tasks[x[0]]>=x[1]){s.completed[x[0]]=1;s.cigarettes+=x[2];s.tasks.earned+=x[2];s.respect+=5;msg('🏆 Задание выполнено! +'+x[2]+' 🚬')}})}
function ranks(){let h='<h2>🏆 Звания</h2>';R.forEach(x=>h+='<p>'+(s.points>=x[1]?'✅':'🔒')+' <b>'+x[0]+'</b> — '+fmt(x[1])+' ⭐</p>');h+='<hr><p>💎 Престиж: '+s.prestige+'</p>';openModal(h)}
function npcMenu(){let h='<h2>🧑‍🤝‍🧑 NPC</h2><p>Теперь с персонажами можно взаимодействовать:</p><div class="shop-grid">';Object.entries(NPCS).forEach(([id,n])=>{h+='<button type="button" class="npc-btn" data-npc="'+id+'">'+n.icon+' <b>'+n.name+'</b><br><small>'+n.desc+'</small><br>▶ '+n.action+'</button>'});openModal(h+'</div>');document.querySelectorAll('[data-npc]').forEach(b=>b.addEventListener('click',()=>{const n=NPCS[b.dataset.npc];if(!n)return;n.run();ui();save();npcMenu()}))}
function more(){openModal('<h2>☰ Ещё</h2><button type="button" id="npc-btn" style="width:100%;margin-bottom:12px">🧑‍🤝‍🧑 Взаимодействовать с NPC</button><h3>🏆 Достижения</h3><p>Тап-машина, Критический удар, Решала, Пачка за пачкой.</p><h3>💎 Престиж</h3><p>После 25 000 ⭐ можно начать новый срок и сохранить постоянный бонус силы.</p><button type="button" id="prestige">Начать новый срок</button>');const n=$('npc-btn');if(n)n.addEventListener('click',npcMenu);const p=$('prestige');if(p)p.addEventListener('click',()=>{if(s.points<25000){msg('Сначала получи звание «Вор в законе»');return}s.prestige++;s.points=0;s.cigarettes=0;s.power=1+s.prestige;s.currentObject=0;s.completed={};s.tasks={taps:0,crit:0,events:0,earned:0};closeModal();msg('💎 Новый срок! Сила '+s.power);ui();save()})}
function init(){if(started)return;started=true;load();ui();const tapArea=$('tap-area');if(tapArea)tapArea.addEventListener('pointerdown',tap,{passive:false});const shopBtn=$('btn-shop'),rankBtn=$('btn-rank'),tasksBtn=$('btn-tasks'),moreBtn=$('btn-more'),closeBtn=$('modal-close'),overlay=$('modal-overlay');if(shopBtn)shopBtn.addEventListener('click',shop);if(rankBtn)rankBtn.addEventListener('click',ranks);if(tasksBtn)tasksBtn.addEventListener('click',taskMenu);if(moreBtn)moreBtn.addEventListener('click',more);if(closeBtn)closeBtn.addEventListener('click',closeModal);if(overlay)overlay.addEventListener('click',e=>{if(e.target===overlay&&overlay.dataset.locked!=='1')closeModal()});setInterval(()=>{if(s.energy<s.maxEnergy){s.energy=Math.min(s.maxEnergy,s.energy+1);ui();save()}},30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.addEventListener('load',init,{once:true});