/* АВТОРИТЕТ 2.0 — стабильная версия */
'use strict';
const N=['Чахлый','Додик','Дрыщ','Шкет','Хлюпик','Тормоз','Балбес','Лопух','Тюфяк','Заморыш','Пузан','Пельмень','Кочерыжка','Шнурок','Обормот','Кабачок','Мокрый Носок','Кривой Шнурок','Тормозной','Клоп','Пузатый Шкет','Малявка','Руки-Крюки','Горе-Авторитет','Гремлин','Пельмень Без Вилки','Шнурок Без Ботинка','Тапок','Сопливый Шкет','Чайник','Криворукий','Недомерок','Каштан','Мятый','Забытый','Ходячая Ошибка','Кривой Прицел','Потеряшка','Мелкий Косяк','Батон','Вечный Новенький','Шмоня','Картонный Боец','Голова-Кирпич','Тихий Пельмень','Сбитый Прицел','Герой Очереди','Местный Балбес','Почти Пацан','Не Суетись'];
const R=[['Салага',0],['Пацан',100],['Блатной',500],['Смотрящий',2000],['Авторитет',8000],['Вор в законе',25000]];
const O=[['Груша','🥊',1,0],['Сокамерник','👊',1.3,150],['Отжимания','💪',1.6,400],['Тренажёр','🏋️',2.2,1500],['Авторитет','👑',3.2,6000]];
const EVENTS=[['Шмон!','Надзиратели ворвались в камеру. Что делаешь?',[['Спрятать папиросы',.55,40,15],['Стоять спокойно',0,10,5],['Сделать вид, что спишь',.25,5,8]]],['Малява','Тебе передали маляву. Что в ней?',[['Прочитать сразу',.4,30,20],['Спрятать до завтра',.15,15,10],['Выбросить',0,0,3]]],['Посылка','Пришла посылка, но непонятно чья.',[['Забрать себе',.6,60,10],['Отдать смотрящему',0,0,20],['Оставить',.1,0,5]]]];
const FUN=['Надзиратель идёт... сделай умный вид.','Сегодня без шмона. Чудо.','Шайба сказал, что ты нормальный пацан.','Кто-то опять забрал папиросы. Классика.','В столовой сегодня мясо. Или что-то похожее.','Сегодня раздача посылок. Надежда умирает последней.'];
const NPCS={
 шайба:{name:'Шайба',icon:'🧢',desc:'торговец',action:'Попросить скидку',run(){if(s.jailed){msg('🔒 Сначала выйди из карцера');return}const gain=25+s.prestige*5;s.cigarettes+=gain;s.respect+=1;msg('🧢 Шайба помог: +'+gain+' 🚬 и +1 🧠')}},
 бугор:{name:'Бугор',icon:'💪',desc:'даёт задания',action:'Потренироваться',run(){if(s.jailed){msg('🔒 Сначала выйди из карцера');return}if(s.energy<10){msg('⚡ Бугор: сначала восстанови хотя бы 10 энергии');return}s.energy-=10;if(s.energy===s.maxEnergy-10)s.lastEnergyTime=Date.now();s.power++;s.respect+=2;s.points+=15;msg('💪 Бугор потренировал тебя: +1 💪 +2 🧠 +15 ⭐')}},
 косой:{name:'Косой',icon:'😏',desc:'рискованные сделки',action:'Рискнуть',run(){if(s.jailed){msg('🔒 Сначала выйди из карцера');return}const win=Math.random()<.55;if(win){s.cigarettes+=100;s.points+=40;msg('😏 Косой: сделка удалась! +100 🚬 +40 ⭐')}else{s.cigarettes=Math.max(0,s.cigarettes-60);s.points=Math.max(0,s.points-20);msg('😏 Косой: сделка провалилась. -60 🚬 -20 ⭐')}}},
 смотрящий:{name:'Смотрящий',icon:'👑',desc:'следит за продвижением',action:'Получить совет',run(){if(s.jailed){msg('🔒 Сначала выйди из карцера');return}const r=rank();msg('👑 Смотрящий: твой текущий уровень — «'+r[0]+'». Следующая цель: '+fmt((R.find(x=>x[1]>s.points)||R[R.length-1])[1])+' ⭐')}}
};
let s={cigarettes:0,points:0,energy:250,maxEnergy:250,power:1,critChance:.05,respect:0,wealth:0,nickname:'',currentObject:0,prestige:0,upgrades:{power:0,crit:0,energyMax:0},boosters:{double:0},tasks:{taps:0,crit:0,events:0,earned:0,jail:0},completed:{},lastEnergyTime:Date.now(),saveUpdatedAt:Date.now(),lastChoiceEvent:0,totalTaps:0,jailed:false,jailTaps:0,jailRequired:500,confiscatedCigarettes:0,jailProtection:0};
let messageQueue=[],messageBusy=false,activeEvent=false;
const $=id=>document.getElementById(id);
function save(){try{s.saveUpdatedAt=Date.now();localStorage.setItem('avtoritet_save_v2',JSON.stringify(s))}catch(e){}}
function restoreEnergy(now){now=Number(now)||Date.now();if(!Number.isFinite(s.lastEnergyTime))s.lastEnergyTime=now;if(!Number.isFinite(s.energy))s.energy=0;if(!Number.isFinite(s.maxEnergy)||s.maxEnergy<1)s.maxEnergy=250;if(s.energy>=s.maxEnergy){s.energy=s.maxEnergy;s.lastEnergyTime=now;return 0}const elapsed=Math.max(0,now-s.lastEnergyTime),gain=Math.floor(elapsed/30000);if(gain>0){s.energy=Math.min(s.maxEnergy,s.energy+gain);s.lastEnergyTime+=gain*30000;if(s.energy>=s.maxEnergy)s.lastEnergyTime=now}return gain}
function highestUnlocked(){let i=0;for(let j=0;j<O.length;j++)if(s.points>=O[j][3])i=j;return i}
function syncObject(showMessage){const max=highestUnlocked();if(s.currentObject>max)s.currentObject=max;if(s.currentObject===0&&max>0){s.currentObject=max;if(showMessage)msg('🔓 Открыт новый объект: '+O[max][0])}}
function load(){try{const raw=localStorage.getItem('avtoritet_save_v2');if(raw){const d=JSON.parse(raw);if(d&&typeof d==='object')s={...s,...d,upgrades:{...s.upgrades,...(d.upgrades||{})},tasks:{...s.tasks,...(d.tasks||{})},boosters:{...s.boosters,...(d.boosters||{})}}}}catch(e){}if(!s.nickname)s.nickname=N[Math.floor(Math.random()*N.length)];if(!Number.isFinite(s.energy))s.energy=250;if(!Number.isFinite(s.maxEnergy))s.maxEnergy=250;if(!Number.isFinite(s.lastEnergyTime))s.lastEnergyTime=Date.now();if(!Number.isFinite(s.saveUpdatedAt))s.saveUpdatedAt=Date.now();if(!Number.isFinite(s.jailTaps)||s.jailTaps<0)s.jailTaps=0;if(!Number.isFinite(s.jailRequired)||s.jailRequired<1)s.jailRequired=500;if(!Number.isFinite(s.confiscatedCigarettes)||s.confiscatedCigarettes<0)s.confiscatedCigarettes=0;if(!Number.isFinite(s.jailProtection)||s.jailProtection<0)s.jailProtection=0;restoreEnergy(Date.now());syncObject(false);save()}
function fmt(n){n=Math.floor(Number(n)||0);return n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':String(n)}
function rank(){let r=R[0];for(const x of R)if(s.points>=x[1])r=x;return r}
function ui(){const ids=['cigarettes','points','energy','max-energy','nickname','rank','power-stat','respect-stat','wealth-stat','object-emoji','object-name'];if(ids.some(id=>!$(id)))return;$('cigarettes').textContent=fmt(s.cigarettes);$('points').textContent=fmt(s.points);$('energy').textContent=Math.floor(s.energy);$('max-energy').textContent=s.maxEnergy;$('nickname').textContent=s.nickname;$('rank').textContent=rank()[0];$('power-stat').textContent=s.power;$('respect-stat').textContent=s.respect;$('wealth-stat').textContent=s.wealth;const o=O[s.currentObject]||O[0];$('object-emoji').textContent=s.jailed?'⛓️':o[1];$('object-name').textContent=s.jailed?'Карцер':o[0];const gc=$('game-container');if(gc)gc.classList.toggle('jail-mode',!!s.jailed);const jp=$('jail-panel');if(jp){jp.classList.toggle('hidden',!s.jailed);if(s.jailed){$('jail-count').textContent=Math.min(s.jailTaps,s.jailRequired)+' / '+s.jailRequired;$('jail-left').textContent=Math.max(0,s.jailRequired-s.jailTaps)}else{$('jail-count').textContent='0 / '+s.jailRequired;$('jail-left').textContent=s.jailRequired}}['btn-shop','btn-rank','btn-tasks','btn-more'].forEach(id=>{const b=$(id);if(b)b.disabled=!!s.jailed})}
function msg(x){messageQueue.push(String(x));processMessages()}
function processMessages(){if(messageBusy||!messageQueue.length)return;const e=$('event-message');if(!e){messageQueue=[];return}messageBusy=true;e.textContent=messageQueue.shift();e.classList.add('show');setTimeout(()=>{e.classList.remove('show');setTimeout(()=>{messageBusy=false;processMessages()},250)},4200)}
function feedback(e,n,c){const x=$('tap-feedback');if(!x)return;x.textContent=(c?'КРИТ! ':'+')+n;x.style.left=(e&&e.clientX||150)+'px';x.style.top=(e&&e.clientY||250)+'px';x.classList.remove('show');void x.offsetWidth;x.classList.add('show')}
function jailTap(e){if(!s.jailed)return;e&&e.preventDefault&&e.preventDefault();if(s.jailTaps>=s.jailRequired)return;s.jailTaps++;const t=$('tap-object');if(t){t.classList.remove('punch');void t.offsetWidth;t.classList.add('punch')}feedback(e,1,false);if(s.jailTaps>=s.jailRequired)releaseFromJail();else ui();save()}
function releaseFromJail(){const confiscated=Math.max(0,Math.floor(s.confiscatedCigarettes));s.jailed=false;s.cigarettes+=confiscated;s.confiscatedCigarettes=0;s.jailTaps=0;s.tasks.jail=(s.tasks.jail||0)+1;s.jailProtection=75;msg('🔓 Карцер пройден! Тебя выпустили. 🚬 Конфискованные сигареты возвращены: '+fmt(confiscated));tasksCheck();ui();save()}
function enterJail(reason){if(s.jailed)return;s.jailed=true;s.jailRequired=500;s.jailTaps=0;s.confiscatedCigarettes=Math.max(0,Math.floor(s.cigarettes));s.cigarettes=0;s.jailProtection=0;activeEvent=false;const o=$('modal-overlay');if(o){o.dataset.locked='0';o.classList.add('hidden')}msg('🚨 Ты загремел в карцер! Все сигареты временно изъяты.');if(reason)msg(reason+' Отсидеть: 500 тапов.');ui();save()}
function tap(e){if(s.jailed){jailTap(e);return}if(activeEvent)return;e&&e.preventDefault&&e.preventDefault();restoreEnergy(Date.now());if(s.energy<1){msg('⚡ Энергия закончилась. Отдохни или используй бонус.');return}s.energy--;s.totalTaps++;s.tasks.taps++;if(s.energy===s.maxEnergy-1)s.lastEnergyTime=Date.now();if(s.jailProtection>0)s.jailProtection--;let g=s.power*O[s.currentObject][2];const c=Math.random()<s.critChance;if(c){g*=2;s.tasks.crit++}if(s.boosters.double>0){g*=2;s.boosters.double--}s.cigarettes+=g;s.tasks.earned+=g;s.points+=g*.8;const t=$('tap-object');if(t){t.classList.remove('punch');void t.offsetWidth;t.classList.add('punch')}feedback(e,Math.floor(g),c);const old=s.currentObject;syncObject(true);if(old!==s.currentObject)ui();if(Math.random()<.025)msg(FUN[Math.floor(Math.random()*FUN.length)]);if(Math.random()<.012&&s.points-s.lastChoiceEvent>30)openEvent();tasksCheck();ui();save()}
function openModal(h,locked=false){if(s.jailed)return;const c=$('modal-content'),o=$('modal-overlay');if(!c||!o)return;c.innerHTML=h;o.classList.remove('hidden');o.dataset.locked=locked?'1':'0'}
function closeModal(){const o=$('modal-overlay');if(!o)return;if(o.dataset.locked==='1')return;o.classList.add('hidden')}
function finishEvent(){activeEvent=false;const o=$('modal-overlay');if(o)o.dataset.locked='0';closeModal();tasksCheck();ui();save()}
function openEvent(){if(s.jailed||activeEvent)return;activeEvent=true;const v=EVENTS[Math.floor(Math.random()*EVENTS.length)];let h='<h2>⚠️ '+v[0]+'</h2><p>'+v[1]+'</p><p><b>Выбери один вариант:</b></p><div class="choices">';v[2].forEach((c,i)=>h+='<button type="button" class="choice" data-i="'+i+'">'+c[0]+'</button>');openModal(h+'</div>',true);document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>{if(!activeEvent||s.jailed)return;const c=v[2][Number(b.dataset.i)];s.tasks.events++;s.lastChoiceEvent=s.points;if(Math.random()>c[1]){s.cigarettes+=c[2];s.tasks.earned+=c[2];s.points+=c[3];s.respect+=Math.floor(c[3]/5);msg('Удачно! +'+c[2]+' 🚬 +'+c[3]+' ⭐');finishEvent()}else{const loss=Math.max(3,Math.ceil(c[3]*1.5));s.points=Math.max(0,s.points-loss);if(c[1]>0&&s.jailProtection<=0&&Math.random()<.04){finishEvent();enterJail('❌ Рискованный ход провалился.');}else{msg('Не повезло. Авторитет пострадал.');finishEvent()}}}))}
function objectMenu(){if(s.jailed)return;let max=highestUnlocked(),h='<h2>🥊 Объекты</h2><p>Каждый новый объект увеличивает доход за тап.</p><div class="shop-grid">';O.forEach((o,i)=>{const unlocked=i<=max;h+='<button type="button" data-o="'+i+'" '+(unlocked?'':'disabled')+'>'+o[1]+' '+o[0]+'<br>×'+o[2]+' · '+(unlocked?'Открыт':'🔒 '+fmt(o[3])+' ⭐')+(i===s.currentObject?' · ВЫБРАН':'')+'</button>'});openModal(h+'</div>');document.querySelectorAll('[data-o]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.o);if(i>highestUnlocked()||s.jailed)return;s.currentObject=i;ui();save();objectMenu()}))}
function shop(){if(s.jailed){msg('🔒 Магазин закрыт до выхода из карцера');return}openModal('<h2>🛒 Магазин</h2><div class="shop-grid"><button type="button" data-b="p">💪 Сила<br>Цена '+(100+s.upgrades.power*250)+'</button><button type="button" data-b="c">🎯 Крит<br>Цена '+(300+s.upgrades.crit*500)+'</button><button type="button" data-b="e">⚡ Энергия<br>Цена '+(400+s.upgrades.energyMax*700)+'</button><button type="button" data-b="d">🔥 ×2 на 100 тапов<br>Цена 500</button></div><button type="button" id="objects-btn" style="width:100%;margin-top:10px">🥊 Выбрать объект</button>');document.querySelectorAll('[data-b]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.b,cost=type==='p'?100+s.upgrades.power*250:type==='c'?300+s.upgrades.crit*500:type==='e'?400+s.upgrades.energyMax*700:500;if(s.cigarettes<cost){msg('🚬 Не хватает сигарет. Нужно '+cost+'.');return}s.cigarettes-=cost;if(type==='p'){s.power++;s.upgrades.power++}if(type==='c'){s.critChance=Math.min(.5,s.critChance+.02);s.upgrades.crit++}if(type==='e'){s.maxEnergy+=25;s.energy=s.maxEnergy;s.upgrades.energyMax++;s.lastEnergyTime=Date.now()}if(type==='d')s.boosters.double+=100;ui();save();shop()}));const ob=$('objects-btn');if(ob)ob.onclick=objectMenu}
function rankMenu(){if(s.jailed)return;openModal('<h2>🏆 Масть</h2><p>Твоя масть: <b>'+rank()[0]+'</b></p><p>Следующая ступень: '+((R.find(x=>x[1]>s.points)||R[R.length-1])[0])+' · '+fmt((R.find(x=>x[1]>s.points)||R[R.length-1])[1])+' ⭐</p>')}
function tasksCheck(){if(!s.tasks)return}
function tasksMenu(){if(s.jailed)return;openModal('<h2>🎯 Поручения</h2><p>Тапы: '+s.tasks.taps+'</p><p>Криты: '+s.tasks.crit+'</p><p>События: '+s.tasks.events+'</p><p>Карcer: '+s.tasks.jail+'/2</p>')}
function more(){if(s.jailed)return;openModal('<h2>☰ Барак</h2><p>Здесь можно открыть NPC, достижения и новый срок.</p>')}
function init(){load();ui();const tapArea=$('tap-area');if(tapArea){tapArea.addEventListener('click',tap);tapArea.addEventListener('touchstart',tap,{passive:false})}const close=$('modal-close');if(close)close.addEventListener('click',closeModal);const bs=[['btn-shop',shop],['btn-rank',rankMenu],['btn-tasks',tasksMenu],['btn-more',more]];bs.forEach(([id,fn])=>{const b=$(id);if(b)b.addEventListener('click',fn)});setInterval(()=>{if(!s.jailed){const gain=restoreEnergy(Date.now());if(gain>0){ui();save()}}},1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
