/* АВТОРИТЕТ 2.0 — стабильная версия */
'use strict';
const REWARDED_AD_UNIT='/YOUR_NETWORK_CODE/YOUR_REWARDED_AD_UNIT';
const REWARDED_AD_ENABLED=!REWARDED_AD_UNIT.includes('YOUR_');
const N=['Кирпич','Шайба','Бугор','Хмурый','Косой','Гвоздь','Топор','Серый','Лысый','Крест','Малой','Брат','Штиль','Волк','Кабан','Ёжик','Пупс','Змей','Тигр','Кощей','Батя','Шустрый','Немой','Гроза'];
const R=[['Салага',0],['Пацан',100],['Блатной',500],['Смотрящий',2000],['Авторитет',8000],['Вор в законе',25000]];
const O=[['Груша','🥊',1,0],['Сокамерник','👊',1.3,150],['Отжимания','💪',1.6,400],['Тренажёр','🏋️',2.2,1500],['Авторитет','👑',3.2,6000]];
const EVENTS=[['Шмон!','Надзиратели ворвались в камеру. Что делаешь?',[['Спрятать папиросы',.55,40,15],['Стоять спокойно',0,10,5],['Сделать вид, что спишь',.25,5,8]]],['Малява','Тебе передали маляву. Что в ней?',[['Прочитать сразу',.4,30,20],['Спрятать до завтра',.15,15,10],['Выбросить',0,0,3]]],['Посылка','Пришла посылка, но непонятно чья.',[['Забрать себе',.6,60,10],['Отдать смотрящему',0,0,20],['Оставить',.1,0,5]]]];
const FUN=['Надзиратель идёт... сделай умный вид.','Сегодня без шмона. Чудо.','Шайба сказал, что ты нормальный пацан.','Кто-то опять забрал папиросы. Классика.','В столовой сегодня мясо. Или что-то похожее.','Сегодня раздача посылок. Надежда умирает последней.'];
const NPCS={
 шайба:{name:'Шайба',icon:'🧢',desc:'торговец',action:'Попросить скидку',run(){if(s.jailed){msg('🔒 Сначала выйди из карцера');return}const gain=25+s.prestige*5;s.cigarettes+=gain;s.respect+=1;msg('🧢 Шайба помог: +'+gain+' 🚬 и +1 🧠')}},
 бугор:{name:'Бугор',icon:'💪',desc:'даёт задания',action:'Потренироваться',run(){if(s.jailed){msg('🔒 Сначала выйди из карцера');return}if(s.energy<10){msg('⚡ Бугор: сначала восстанови хотя бы 10 энергии');return}s.energy-=10;s.power++;s.respect+=2;s.points+=15;msg('💪 Бугор потренировал тебя: +1 💪 +2 🧠 +15 ⭐')}},
 косой:{name:'Косой',icon:'😏',desc:'рискованные сделки',action:'Рискнуть',run(){if(s.jailed){msg('🔒 Сначала выйди из карцера');return}const win=Math.random()<.55;if(win){s.cigarettes+=100;s.points+=40;msg('😏 Косой: сделка удалась! +100 🚬 +40 ⭐')}else{s.cigarettes=Math.max(0,s.cigarettes-60);s.points=Math.max(0,s.points-20);msg('😏 Косой: сделка провалилась. -60 🚬 -20 ⭐')}}},
 смотрящий:{name:'Смотрящий',icon:'👑',desc:'следит за продвижением',action:'Получить совет',run(){if(s.jailed){msg('🔒 Сначала выйди из карцера');return}const r=rank();msg('👑 Смотрящий: твой текущий уровень — «'+r[0]+'». Следующая цель: '+fmt((R.find(x=>x[1]>s.points)||R[R.length-1])[1])+' ⭐')}}
};
let s={cigarettes:0,points:0,energy:250,maxEnergy:250,power:1,critChance:.05,respect:0,wealth:0,nickname:'',currentObject:0,prestige:0,upgrades:{power:0,crit:0,energyMax:0},boosters:{double:0},tasks:{taps:0,crit:0,events:0,earned:0,jail:0},completed:{},lastEnergyTime:Date.now(),lastChoiceEvent:0,totalTaps:0,jailed:false,jailTaps:0,jailRequired:500,confiscatedCigarettes:0};
let started=false,messageQueue=[],messageBusy=false,activeEvent=false;
let rewardedSlot=null,pendingNickname='',rewardGranted=false,rewardedListenersReady=false,rewardTimeout=null;
const $=id=>document.getElementById(id);
function save(){try{s.lastEnergyTime=Date.now();localStorage.setItem('avtoritet_save_v2',JSON.stringify(s))}catch(e){}}
function highestUnlocked(){let i=0;for(let j=0;j<O.length;j++)if(s.points>=O[j][3])i=j;return i}
function syncObject(showMessage){const max=highestUnlocked();if(s.currentObject>max)s.currentObject=max;if(s.currentObject===0&&max>0){s.currentObject=max;if(showMessage)msg('🔓 Открыт новый объект: '+O[max][0])}}
function load(){try{const raw=localStorage.getItem('avtoritet_save_v2');if(raw){const d=JSON.parse(raw);if(d&&typeof d==='object')s={...s,...d,upgrades:{...s.upgrades,...(d.upgrades||{})},tasks:{...s.tasks,...(d.tasks||{})},boosters:{...s.boosters,...(d.boosters||{})}}}}catch(e){}if(!s.nickname)s.nickname=N[Math.floor(Math.random()*N.length)];if(!Number.isFinite(s.energy))s.energy=250;if(!Number.isFinite(s.maxEnergy))s.maxEnergy=250;if(!Number.isFinite(s.lastEnergyTime))s.lastEnergyTime=Date.now();if(!Number.isFinite(s.jailTaps)||s.jailTaps<0)s.jailTaps=0;if(!Number.isFinite(s.jailRequired)||s.jailRequired<1)s.jailRequired=500;if(!Number.isFinite(s.confiscatedCigarettes)||s.confiscatedCigarettes<0)s.confiscatedCigarettes=0;s.energy=Math.min(s.maxEnergy,s.energy+Math.floor(Math.max(0,Date.now()-s.lastEnergyTime)/30000));syncObject(false)}
function fmt(n){n=Math.floor(Number(n)||0);return n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':String(n)}
function rank(){let r=R[0];for(const x of R)if(s.points>=x[1])r=x;return r}
function ui(){const ids=['cigarettes','points','energy','max-energy','nickname','rank','power-stat','respect-stat','wealth-stat','object-emoji','object-name'];if(ids.some(id=>!$(id)))return;$('cigarettes').textContent=fmt(s.cigarettes);$('points').textContent=fmt(s.points);$('energy').textContent=Math.floor(s.energy);$('max-energy').textContent=s.maxEnergy;$('nickname').textContent=s.nickname;$('rank').textContent=rank()[0];$('power-stat').textContent=s.power;$('respect-stat').textContent=s.respect;$('wealth-stat').textContent=s.wealth;const o=O[s.currentObject]||O[0];$('object-emoji').textContent=s.jailed?'⛓️':o[1];$('object-name').textContent=s.jailed?'Карцер':o[0];const gc=$('game-container');if(gc)gc.classList.toggle('jail-mode',!!s.jailed);const jp=$('jail-panel');if(jp){jp.classList.toggle('hidden',!s.jailed);if(s.jailed){$('jail-count').textContent=Math.min(s.jailTaps,s.jailRequired)+' / '+s.jailRequired;$('jail-left').textContent=Math.max(0,s.jailRequired-s.jailTaps)}else{$('jail-count').textContent='0 / '+s.jailRequired;$('jail-left').textContent=s.jailRequired}}['btn-shop','btn-rank','btn-tasks','btn-more'].forEach(id=>{const b=$(id);if(b)b.disabled=!!s.jailed})}
function msg(x){messageQueue.push(String(x));processMessages()}
function processMessages(){if(messageBusy||!messageQueue.length)return;const e=$('event-message');if(!e){messageQueue=[];return}messageBusy=true;e.textContent=messageQueue.shift();e.classList.add('show');setTimeout(()=>{e.classList.remove('show');setTimeout(()=>{messageBusy=false;processMessages()},250)},4200)}
function feedback(e,n,c){const x=$('tap-feedback');if(!x)return;x.textContent=(c?'КРИТ! ':'+')+n;x.style.left=(e&&e.clientX||150)+'px';x.style.top=(e&&e.clientY||250)+'px';x.classList.remove('show');void x.offsetWidth;x.classList.add('show')}
function jailTap(e){if(!s.jailed)return;e&&e.preventDefault&&e.preventDefault();if(s.jailTaps>=s.jailRequired)return;s.jailTaps++;const t=$('tap-object');if(t){t.classList.remove('punch');void t.offsetWidth;t.classList.add('punch')}feedback(e,1,false);if(s.jailTaps>=s.jailRequired)releaseFromJail();else ui();save()}
function releaseFromJail(){const confiscated=Math.max(0,Math.floor(s.confiscatedCigarettes));s.jailed=false;s.cigarettes+=confiscated;s.confiscatedCigarettes=0;s.jailTaps=0;s.tasks.jail=(s.tasks.jail||0)+1;msg('🔓 Карцер пройден! Тебя выпустили. 🚬 Конфискованные сигареты возвращены: '+fmt(confiscated));tasksCheck();ui();save()}
function enterJail(reason){if(s.jailed)return;s.jailed=true;s.jailRequired=500;s.jailTaps=0;s.confiscatedCigarettes=Math.max(0,Math.floor(s.cigarettes));s.cigarettes=0;activeEvent=false;const o=$('modal-overlay');if(o){o.dataset.locked='0';o.classList.add('hidden')}msg('🚨 Ты загремел в карцер! Все сигареты временно изъяты.');if(reason)msg(reason+' Отсидеть: 500 тапов.');ui();save()}
function tap(e){if(s.jailed){jailTap(e);return}if(activeEvent)return;if(s.energy<1){msg('⚡ Энергия закончилась. Отдохни или используй бонус.');return}e&&e.preventDefault&&e.preventDefault();s.energy--;s.totalTaps++;s.tasks.taps++;let g=s.power*O[s.currentObject][2];const c=Math.random()<s.critChance;if(c){g*=2;s.tasks.crit++}if(s.boosters.double>0){g*=2;s.boosters.double--}s.cigarettes+=g;s.tasks.earned+=g;s.points+=g*.8;const t=$('tap-object');if(t){t.classList.remove('punch');void t.offsetWidth;t.classList.add('punch')}feedback(e,Math.floor(g),c);const old=s.currentObject;syncObject(true);if(old!==s.currentObject)ui();if(Math.random()<.025)msg(FUN[Math.floor(Math.random()*FUN.length)]);if(Math.random()<.012&&s.points-s.lastChoiceEvent>30)openEvent();tasksCheck();ui();save()}
function openModal(h,locked=false){if(s.jailed)return;const c=$('modal-content'),o=$('modal-overlay');if(!c||!o)return;c.innerHTML=h;o.classList.remove('hidden');o.dataset.locked=locked?'1':'0'}
function closeModal(){const o=$('modal-overlay');if(!o)return;if(o.dataset.locked==='1')return;o.classList.add('hidden')}
function finishEvent(){activeEvent=false;const o=$('modal-overlay');if(o)o.dataset.locked='0';closeModal();tasksCheck();ui();save()}
function openEvent(){if(s.jailed||activeEvent)return;activeEvent=true;const v=EVENTS[Math.floor(Math.random()*EVENTS.length)];let h='<h2>⚠️ '+v[0]+'</h2><p>'+v[1]+'</p><p><b>Выбери один вариант:</b></p><div class="choices">';v[2].forEach((c,i)=>h+='<button type="button" class="choice" data-i="'+i+'">'+c[0]+'</button>');openModal(h+'</div>',true);document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>{if(!activeEvent||s.jailed)return;const c=v[2][Number(b.dataset.i)];s.tasks.events++;if(Math.random()>c[1]){s.cigarettes+=c[2];s.tasks.earned+=c[2];s.points+=c[3];s.respect+=Math.floor(c[3]/5);msg('Удачно! +'+c[2]+' 🚬 +'+c[3]+' ⭐');finishEvent()}else{const loss=Math.max(3,Math.ceil(c[3]*1.5));s.points=Math.max(0,s.points-loss);if(c[1]>0&&Math.random()<.45){finishEvent();enterJail('❌ Рискованный ход провалился.');}else{msg('Не повезло. Авторитет пострадал.');finishEvent()}}}))}
function objectMenu(){if(s.jailed)return;let max=highestUnlocked(),h='<h2>🥊 Объекты</h2><p>Каждый новый объект увеличивает доход за тап.</p><div class="shop-grid">';O.forEach((o,i)=>{const unlocked=i<=max;h+='<button type="button" data-o="'+i+'" '+(unlocked?'':'disabled')+'>'+o[1]+' '+o[0]+'<br>×'+o[2]+' · '+(unlocked?'Открыт':'🔒 '+fmt(o[3])+' ⭐')+(i===s.currentObject?' · ВЫБРАН':'')+'</button>'});openModal(h+'</div>');document.querySelectorAll('[data-o]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.o);if(i>highestUnlocked()||s.jailed)return;s.currentObject=i;ui();save();objectMenu()}))}
function shop(){if(s.jailed){msg('🔒 Магазин закрыт до выхода из карцера');return}openModal('<h2>🛒 Магазин</h2><div class="shop-grid"><button type="button" data-b="p">💪 Сила<br>Цена '+(100+s.upgrades.power*250)+'</button><button type="button" data-b="c">🎯 Крит<br>Цена '+(300+s.upgrades.crit*500)+'</button><button type="button" data-b="e">⚡ Энергия<br>Цена '+(400+s.upgrades.energyMax*700)+'</button><button type="button" data-b="d">🔥 ×2 на 100 тапов<br>Цена 500</button></div><button type="button" id="objects-btn" style="width:100%;margin-top:10px">🥊 Выбрать объект</button>');document.querySelectorAll('[data-b]').forEach(b=>b.addEventListener('click',()=>buy(b.dataset.b)));const ob=$('objects-btn');if(ob)ob.addEventListener('click',objectMenu)}
function buy(k){if(s.jailed)return;const p=k==='p'?100+s.upgrades.power*250:k==='c'?300+s.upgrades.crit*500:k==='e'?400+s.upgrades.energyMax*700:500;if(s.cigarettes<p){msg('Не хватает сигарет');return}s.cigarettes-=p;if(k==='p'){s.power++;s.upgrades.power++}else if(k==='c'){s.critChance=Math.min(.5,s.critChance+.02);s.upgrades.crit++}else if(k==='e'){s.maxEnergy+=25;s.energy+=25;s.upgrades.energyMax++}else{s.boosters.double=(s.boosters.double||0)+100;msg('🔥 Бустер: следующие 100 тапов ×2')}ui();save();shop()}
function taskMenu(){if(s.jailed){msg('🔒 Задания недоступны в карцере');return}const q=[['taps','500 тапов',500,100],['crit','20 критов',20,150],['events','3 события',3,200],['earned','1000 сигарет',1000,250],['jail','Отсидеть 2 раза в карцере',2,300]];let h='<h2>🎯 Задания</h2>';q.forEach(x=>h+='<p>'+(s.completed[x[0]]?'✅':'⬜')+' '+x[1]+' — '+x[3]+' 🚬'+(x[0]==='jail'?' ('+(s.tasks.jail||0)+'/2)':'' )+'</p>');openModal(h)}
function tasksCheck(){[['taps',500,100],['crit',20,150],['events',3,200],['earned',1000,250],['jail',2,300]].forEach(x=>{if(!s.completed[x[0]]&&(s.tasks[x[0]]||0)>=x[1]){s.completed[x[0]]=1;s.cigarettes+=x[2];s.tasks.earned+=x[2];s.respect+=5;msg('🏆 Задание выполнено! +'+x[2]+' 🚬')}})}
function ranks(){if(s.jailed){msg('🔒 Звания недоступны в карцере');return}let h='<h2>🏆 Звания</h2>';R.forEach(x=>h+='<p>'+(s.points>=x[1]?'✅':'🔒')+' <b>'+x[0]+'</b> — '+fmt(x[1])+' ⭐</p>');h+='<hr><p>💎 Престиж: '+s.prestige+'</p>';openModal(h)}
function npcMenu(){if(s.jailed){msg('🔒 NPC недоступны в карцере');return}let h='<h2>🧑‍🤝‍🧑 NPC</h2><p>Теперь с персонажами можно взаимодействовать:</p><div class="shop-grid">';Object.entries(NPCS).forEach(([id,n])=>{h+='<button type="button" class="npc-btn" data-npc="'+id+'">'+n.icon+' <b>'+n.name+'</b><br><small>'+n.desc+'</small><br>▶ '+n.action+'</button>'});openModal(h+'</div>');document.querySelectorAll('[data-npc]').forEach(b=>b.addEventListener('click',()=>{const n=NPCS[b.dataset.npc];if(!n)return;n.run();ui();save();npcMenu()}))}
function esc(x){return String(x).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function nameMenu(){if(s.jailed){msg('🔒 Имя можно менять после выхода из карцера');return}const current=esc(s.nickname);openModal('<h2>✏️ Имя</h2><p>Текущее имя: <b>'+current+'</b></p><input id="nickname-input" maxlength="18" autocomplete="off" value="'+current+'" placeholder="Новое имя" style="width:100%;padding:12px;border:1px solid #555;border-radius:10px;background:#252525;color:#fff;margin:8px 0 10px"><p style="color:#bbb">Смена имени доступна за добровольный просмотр рекламы.</p><button type="button" id="watch-name-ad" style="width:100%;padding:13px;border:1px solid #555;border-radius:12px;background:#292929;color:#fff;font-weight:800">📺 Посмотреть рекламу и сменить имя</button>');const b=$('watch-name-ad');if(b)b.addEventListener('click',requestNameChange)}
function requestNameChange(){if(s.jailed)return;const input=$('nickname-input');if(!input)return;const name=input.value.trim();if(!/^[\p{L}\p{N}_ -]{2,18}$/u.test(name)){msg('Имя: 2–18 символов, только буквы, цифры, пробел, _ или -');return}if(!REWARDED_AD_ENABLED){msg('📺 Реклама пока не подключена. Нужен Ad Unit ID.');return}if(rewardedSlot||pendingNickname){msg('📺 Реклама уже загружается.');return}pendingNickname=name;rewardGranted=false;if(rewardTimeout)clearTimeout(rewardTimeout);rewardTimeout=setTimeout(()=>{if(pendingNickname&&!rewardGranted){pendingNickname='';rewardedSlot=null;msg('📺 Не удалось загрузить рекламу. Попробуй ещё раз.')}},20000);window.googletag=window.googletag||{cmd:[]};googletag.cmd.push(()=>{const slot=googletag.defineOutOfPageSlot(REWARDED_AD_UNIT,googletag.enums.OutOfPageFormat.REWARDED);if(!slot){pendingNickname='';clearTimeout(rewardTimeout);rewardTimeout=null;msg('📺 Реклама недоступна на этом устройстве.');return}rewardedSlot=slot;slot.addService(googletag.pubads());googletag.display(slot)})}
function initRewardedAds(){if(rewardedListenersReady||!REWARDED_AD_ENABLED)return;rewardedListenersReady=true;window.googletag=window.googletag||{cmd:[]};googletag.cmd.push(()=>{googletag.pubads().addEventListener('rewardedSlotReady',evt=>{if(evt.slot!==rewardedSlot)return;if(pendingNickname)evt.makeRewardedVisible()});googletag.pubads().addEventListener('rewardedSlotGranted',evt=>{if(evt.slot!==rewardedSlot)return;if(!pendingNickname)return;rewardGranted=true;const newName=pendingNickname;pendingNickname='';if(rewardTimeout)clearTimeout(rewardTimeout);rewardTimeout=null;s.nickname=newName;ui();save();msg('✅ Имя изменено на «'+newName+'»')});googletag.pubads().addEventListener('rewardedSlotClosed',evt=>{if(evt.slot!==rewardedSlot)return;const slot=rewardedSlot;rewardedSlot=null;if(!rewardGranted){pendingNickname='';if(rewardTimeout)clearTimeout(rewardTimeout);rewardTimeout=null;msg('📺 Реклама закрыта до получения награды. Имя не изменено.')}googletag.destroySlots([slot]);rewardGranted=false})})}
function more(){if(s.jailed){msg('🔒 Меню недоступно в карцере');return}openModal('<h2>☰ Ещё</h2><button type="button" id="name-btn" style="width:100%;margin-bottom:10px">✏️ Сменить имя — за рекламу</button><button type="button" id="npc-btn" style="width:100%;margin-bottom:12px">🧑‍🤝‍🧑 Взаимодействовать с NPC</button><h3>🏆 Достижения</h3><p>Тап-машина, Критический удар, Решала, Пачка за пачкой.</p><h3>💎 Престиж</h3><p>После 25 000 ⭐ можно начать новый срок и сохранить постоянный бонус силы.</p><button type="button" id="prestige">Начать новый срок</button>');const nameBtn=$('name-btn'),n=$('npc-btn'),p=$('prestige');if(nameBtn)nameBtn.addEventListener('click',nameMenu);if(n)n.addEventListener('click',npcMenu);if(p)p.addEventListener('click',()=>{if(s.points<25000){msg('Сначала получи звание «Вор в законе»');return}s.prestige++;s.points=0;s.cigarettes=0;s.power=1+s.prestige;s.currentObject=0;s.completed={};s.tasks={taps:0,crit:0,events:0,earned:0,jail:0};closeModal();msg('💎 Новый срок! Сила '+s.power);ui();save()})}
function init(){if(started)return;started=true;load();ui();initRewardedAds();const tapArea=$('tap-area');if(tapArea)tapArea.addEventListener('pointerdown',tap,{passive:false});const shopBtn=$('btn-shop'),rankBtn=$('btn-rank'),tasksBtn=$('btn-tasks'),moreBtn=$('btn-more'),closeBtn=$('modal-close'),overlay=$('modal-overlay');if(shopBtn)shopBtn.addEventListener('click',shop);if(rankBtn)rankBtn.addEventListener('click',ranks);if(tasksBtn)tasksBtn.addEventListener('click',taskMenu);if(moreBtn)moreBtn.addEventListener('click',more);if(closeBtn)closeBtn.addEventListener('click',closeModal);if(overlay)overlay.addEventListener('click',e=>{if(e.target===overlay&&overlay.dataset.locked!=='1')closeModal()});setInterval(()=>{if(s.energy<s.maxEnergy&&!s.jailed){s.energy=Math.min(s.maxEnergy,s.energy+1);ui();save()}},30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.addEventListener('load',init,{once:true});
