'use strict';
(function(){
  const KEY='avtoritet_health_v1';
  const MAX=100;
  const PONT_COST=250;
  const PONT_HEAL=10;
  const $=id=>document.getElementById(id);
  function read(){try{return JSON.parse(localStorage.getItem('avtoritet_save_v2')||'{}')||{}}catch(e){return {}}}
  function write(s){try{localStorage.setItem('avtoritet_save_v2',JSON.stringify(s));return true}catch(e){return false}}
  function health(){const s=read();let h=Number(s.health);if(!Number.isFinite(h))h=MAX;return Math.max(0,Math.min(MAX,h))}
  function setHealth(h){const s=read();s.health=Math.max(0,Math.min(MAX,Math.round(h)));write(s);render();if(s.health<=0)gameOver()}
  function rankIndex(points){const r=[0,100,500,2000,8000,25000];let i=0;for(let j=0;j<r.length;j++)if(points>=r[j])i=j;return i}
  function healAd(){if(typeof window.showRewardedAd==='function')window.showRewardedAd(()=>setHealth(MAX));else msg('📺 Rewarded-реклама пока не подключена.');}
  function healPoints(){const s=read();if(Number(s.points||0)<PONT_COST){msg('⭐ Нужно '+PONT_COST+' понтов для восстановления '+PONT_HEAL+'% здоровья.');return}s.points-=PONT_COST;s.health=Math.min(MAX,(Number(s.health)||0)+PONT_HEAL);write(s);render();msg('🩹 За '+PONT_COST+' понтов восстановлено +'+PONT_HEAL+'% здоровья.');}
  function gameOver(){const c=$('modal-content'),o=$('modal-overlay');if(!c||!o)return;o.dataset.locked='1';o.classList.remove('hidden');c.innerHTML='<h2>☠️ Срок окончен</h2><p>Здоровье закончилось. Авторитет потерян.</p><p>Придётся начинать с нуля.</p><button type="button" id="restart-game" style="width:100%;padding:13px">🔄 Начать сначала</button>';const b=$('restart-game');if(b)b.onclick=()=>{localStorage.removeItem('avtoritet_save_v2');localStorage.removeItem('avtoritet_health_v1');location.reload()}}
  function render(){let box=$('health-box');if(!box){const p=$('player-info');if(!p)return;box=document.createElement('div');box.id='health-box';box.style='margin-top:6px;text-align:center';p.appendChild(box)}const h=health();box.innerHTML='<div>❤️ Здоровье: <b>'+h+'%</b></div><div style="height:8px;background:#333;border-radius:6px;overflow:hidden;margin:4px 18px"><div style="width:'+h+'%;height:100%;background:#d33"></div></div><div style="display:flex;gap:6px;justify-content:center;margin-top:5px"><button type="button" id="health-ad">🎬 Восстановить 100%</button><button type="button" id="health-points">⭐ +10% за '+PONT_COST+' понтов</button></div>';$('health-ad').onclick=healAd;$('health-points').onclick=healPoints}
  function normalEventDamage(){const before=health();const damage=5+Math.floor(Math.random()*6);setHealth(before-damage);msg('🥊 Негативное происшествие: -'+damage+'% здоровья.');}
  function jailStartCheck(){const s=read();if(!s.jailed)return;const mark=Number(localStorage.getItem(KEY+'_jail_mark')||0);const current=Number(s.totalTaps||0)+Number(s.jailTaps||0);if(!mark||current>mark){localStorage.setItem(KEY+'_jail_mark',String(current));if(Number(s.confiscatedCigarettes||0)>0){s.confiscatedCigarettes=Math.floor(Number(s.confiscatedCigarettes)*0.5);write(s)};setTimeout(jailEvent,700)}}
  function jailEvent(){const s=read();if(!s.jailed)return;const events=[
    {title:'🧹 Надзиратель',text:'Надзиратель требует вымыть пол в коридоре.',a:'Согласиться',b:'Отказаться',c:'Подкупить',run:(x)=>{if(x===0){const i=rankIndex(s.points);if(i>0)s.points=Math.max(0,[0,100,500,2000,8000,25000][i]-1);write(s);msg('🧹 Пришлось мыть пол. Понты просели.')}else if(x===1){const i=rankIndex(s.points);const chance=Math.max(.25,.60-i*.08);if(Math.random()<chance){const d=5+Math.floor(Math.random()*6);s.health=Math.max(0,(Number(s.health)||100)-d);write(s);msg('🥊 За отказ тебя избили: -'+d+'% здоровья.')}else{write(s);msg('😏 Отказ прокатил. Статус помог.')}}else{const pay=Math.floor(Number(s.confiscatedCigarettes||0)*.25);s.confiscatedCigarettes=Math.max(0,Number(s.confiscatedCigarettes||0)-pay);write(s);msg('💸 Подкупил надзирателя. Отдано '+pay+' 🚬.')}}},
    {title:'🤐 Стучать или молчать',text:'Надзиратель предлагает настучать на сокамерника.',a:'Настучать',b:'Промолчать',c:'Перевести стрелки',run:(x)=>{if(x===0){s.points+=10;s.respect=Math.max(0,Number(s.respect||0)-3);write(s);msg('🤐 Ты настучал. +10 ⭐, но уважение -3 🧠.')}else if(x===1){const d=5+Math.floor(Math.random()*6);s.health=Math.max(0,(Number(s.health)||100)-d);write(s);msg('🤐 Молчание не понравилось. -'+d+'% здоровья.')}else{if(Math.random()<.5){s.points=Math.max(0,Number(s.points||0)-15);write(s);msg('😬 Не прокатило. -15 ⭐.')}else{write(s);msg('😏 Увернулся от разговора.')}}}},
    {title:'🚽 Толчок',text:'Тебе приказали отмыть туалет.',a:'Согласиться',b:'Отказаться',c:'Подкупить',run:(x)=>{if(x===0){const i=rankIndex(s.points);if(i>0)s.points=Math.max(0,[0,100,500,2000,8000,25000][i]-1);write(s);msg('🚽 Отмыл толчок. Масть просела на ступень.')}else if(x===1){const i=rankIndex(s.points);const chance=Math.max(.22,.58-i*.08);if(Math.random()<chance){const d=5+Math.floor(Math.random()*6);s.health=Math.max(0,(Number(s.health)||100)-d);write(s);msg('🥊 За отказ прилетело: -'+d+'% здоровья.')}else{write(s);msg('👑 Твой статус заставил их отступить.')} }else{const pay=Math.floor(Number(s.confiscatedCigarettes||0)*.25);s.confiscatedCigarettes=Math.max(0,Number(s.confiscatedCigarettes||0)-pay);write(s);msg('💸 Подкуп сработал. Отдано '+pay+' 🚬.')}}},
    {title:'📦 Чужая посылка',text:'В карцере нашли чужую посылку и спрашивают, чья она.',a:'Взять на себя',b:'Сдать владельца',c:'Молчать',run:(x)=>{if(x===0){s.points=Math.max(0,Number(s.points||0)-20);write(s);msg('📦 Ты взял вину на себя. -20 ⭐.')}else if(x===1){s.respect=Math.max(0,Number(s.respect||0)-5);s.points+=15;write(s);msg('📦 Сдал владельца. +15 ⭐, но -5 🧠.')}else{if(Math.random()<.5){const d=5+Math.floor(Math.random()*6);s.health=Math.max(0,(Number(s.health)||100)-d);write(s);msg('🥊 За молчание прилетело: -'+d+'% здоровья.')}else{write(s);msg('🤐 Молчание осталось незамеченным.')}}}}
  ];
    const e=events[Math.floor(Math.random()*events.length)],o=$('modal-overlay'),c=$('modal-content');if(!o||!c)return;o.dataset.locked='1';o.classList.remove('hidden');c.innerHTML='<h2>'+e.title+'</h2><p>'+e.text+'</p><div class="choices"><button type="button" data-jc="0">'+e.a+'</button><button type="button" data-jc="1">'+e.b+'</button><button type="button" data-jc="2">'+e.c+'</button></div>';c.querySelectorAll('[data-jc]').forEach(b=>b.onclick=()=>{e.run(Number(b.dataset.jc));o.dataset.locked='0';o.classList.add('hidden');render();const x=read();if(Number(x.health||100)<=0)gameOver();else setTimeout(jailEvent,1200)})}
  function interceptNormalChoices(){document.addEventListener('click',e=>{const b=e.target.closest('.choice');if(!b)return;const risk=[.55,0,.25,.4,.15,.6,.1];const p=risk[Math.min(risk.length-1,Number(b.dataset.i)||0)];if(p>0){const roll=Math.random(),fail=roll<=p;if(fail){const old=Math.random;Math.random=()=>0;setTimeout(()=>{Math.random=old;normalEventDamage()},30)}}},true)}
  function init(){render();interceptNormalChoices();setInterval(jailStartCheck,1000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();