'use strict';
(function(){
const K='avtoritet_save_v2',T=[0,100,500,2000,8000,25000],N=['Салага','Пацан','Блатной','Смотрящий','Авторитет','Вор в законе'];let busy=false,count=0;
function read(){try{return JSON.parse(localStorage.getItem(K)||'{}')||{}}catch(e){return {}}}function save(s){try{s.saveUpdatedAt=Date.now();localStorage.setItem(K,JSON.stringify(s));return true}catch(e){return false}}function rank(s){let i=0;for(let j=0;j<T.length;j++)if((+s.points||0)>=T[j])i=j;return i}function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a}function cig(s,b){let m=[1,1.5,2.5,4,7,12][rank(s)],n=Math.min(rnd(Math.round(b*.85*m),Math.round(b*1.15*m)),+s.cigarettes||0);s.cigarettes=Math.max(0,(+s.cigarettes||0)-n);return n}function pts(s,b){let m=[1,1.5,2.5,4,7,12][rank(s)],n=Math.min(rnd(Math.round(b*.85*m),Math.round(b*1.15*m)),+s.points||0);s.points=Math.max(0,(+s.points||0)-n);return n}function demote(s){let i=rank(s);if(!i)return 0;let n=Math.max(0,(+s.points||0)-T[i-1]);s.points=T[i-1];return n}
const events=[
['🧹 Коридор','Надзиратель требует привести коридор в порядок.',[['Согласиться',function(s){let q=Math.random();if(q<.4){save(s);return'Работа прошла спокойно. Ничего не потеряно.'}if(q<.75){let n=pts(s,220);save(s);return'Пришлось отработать. −'+n+' ⭐.'}let i=rank(s),n=demote(s);save(s);return'Зашквар. «'+N[i]+'» → «'+N[rank(s)]+'». −'+n+' ⭐.'}],['Отказаться',function(s){let a=cig(s,550),b=pts(s,70);save(s);return'Отказ обошёлся дорого: −'+a+' 🚬 и −'+b+' ⭐.'}],['Попытаться договориться',function(s){let a=cig(s,1000);save(s);return'Договорились. −'+a+' 🚬. ⭐ сохранены.'}]]],
['🧹 Камера','Требуют привести камеру в порядок.',[['Согласиться',function(s){let q=Math.random();if(q<.42){save(s);return'Повезло. Ничего не потеряно.'}if(q<.74){let n=pts(s,260);save(s);return'Пришлось отработать. −'+n+' ⭐.'}let i=rank(s),n=demote(s);save(s);return'Зашквар. «'+N[i]+'» → «'+N[rank(s)]+'». −'+n+' ⭐.'}],['Отказаться',function(s){let a=cig(s,700),b=pts(s,90);save(s);return'За отказ: −'+a+' 🚬 и −'+b+' ⭐.'}],['Попытаться договориться',function(s){let a=cig(s,1400);save(s);return'Договор сработал. −'+a+' 🚬, ⭐ сохранены.'}]]],
['🤐 Сокамерник','От тебя хотят услышать лишнее.',[['Рассказать',function(s){let q=Math.random();if(q<.45){let n=rnd(80,160);s.points=(+s.points||0)+n;save(s);return'Информация пригодилась. +'+n+' ⭐.'}if(q<.75){let n=pts(s,300);save(s);return'История обернулась боком. −'+n+' ⭐.'}let i=rank(s),n=demote(s);save(s);return'Зашквар. «'+N[i]+'» → «'+N[rank(s)]+'». −'+n+' ⭐.'}],['Промолчать',function(s){let a=cig(s,800),b=pts(s,50);save(s);return'Промолчал. −'+a+' 🚬 и −'+b+' ⭐.'}],['Попытаться договориться',function(s){let a=cig(s,1700);save(s);return'Договорились. −'+a+' 🚬. ⭐ сохранены.'}]]]
];
function show(){if(busy)return;let s=read();if(!s.jailed)return;busy=true;let e=events[Math.floor(Math.random()*events.length)],o=document.getElementById('modal-overlay'),c=document.getElementById('modal-content');if(!o||!c){busy=false;return}o.dataset.locked='1';o.classList.remove('hidden');c.innerHTML='<div class="section-window"><div class="section-kicker">КАРЦЕР</div><h2>'+e[0]+'</h2><p class="section-subtitle">'+e[1]+'</p><div class="choices">'+e[2].map((v,i)=>'<button type="button" data-p="'+i+'">'+v[0]+'</button>').join('')+'</div></div>';c.querySelectorAll('[data-p]').forEach(b=>b.onclick=function(){let x=read(),text=e[2][+b.dataset.p][1](x);if(typeof window.msg==='function')window.msg(text);o.dataset.locked='0';o.classList.add('hidden');busy=false;count++;if(typeof window.ui==='function')window.ui()})}
function check(){let s=read();if(!s.jailed){count=0;return}if(count<3&&(+s.jailTaps||0)>=[60,180,320][count]){count++;setTimeout(show,150)}}function init(){let t=document.getElementById('tap-object');if(t)t.addEventListener('click',function(){setTimeout(check,0)},true);check()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();