'use strict';
(function(){
  const $=id=>document.getElementById(id),SAVE_KEY='avtoritet_save_v2';
  const NPCS={
    шайба:{name:'Шайба',icon:'🧢',avatar:'./assets/backgrounds/shaiba_avatar.png',desc:'торгаш',rank:0,action:'Сходить на дело',reward:'25 🚬 +1 🧠',baseChance:70,dialogue:'Есть одно дельце. Небольшое, но шуметь нельзя. Как поступишь?',choices:[{text:'«Сделаю тихо. Без лишнего шума.»',mod:20},{text:'«А чего тянуть? Погнали прямо сейчас.»',mod:5},{text:'«Сначала хочу узнать, что мне с этого.»',mod:-15}]},
    бугор:{name:'Бугор',icon:'💪',avatar:'./assets/backgrounds/Bugor_avatar.png',desc:'тренер',rank:1,action:'Прокачаться',reward:'+1 💪 +2 🧠 +15 ⭐',baseChance:80,dialogue:'Сила — это не только кулаки. Перед тренировкой скажи, что для тебя важнее.',choices:[{text:'«Выносливость. Хочу выдерживать больше.»',mod:15},{text:'«Сила. Мне нужен один мощный удар.»',mod:10},{text:'«Голова. Сначала научусь думать.»',mod:-5}]},
    косой:{name:'Косой',icon:'😏',avatar:'./assets/backgrounds/Kosoy_avatar.png',desc:'решала',rank:2,action:'Рискнуть',reward:'шанс на +100 🚬 +40 ⭐',baseChance:55,dialogue:'Есть сделка. Риск приличный. Я дам тебе один совет — как будешь играть?',choices:[{text:'«Проверю всё дважды. Риск должен быть под контролем.»',mod:20},{text:'«Риск — моё второе имя. Иду ва-банк.»',mod:-5},{text:'«Сначала попробую договориться о лучших условиях.»',mod:10}]},
    смотрящий:{name:'Смотрящий',icon:'👑',avatar:'./assets/backgrounds/Smotraishia_avatar.png',desc:'старший',rank:3,action:'Получить совет',reward:'цель по масти',baseChance:90,dialogue:'Хочешь подняться выше — покажи, что понимаешь главное. Что выберешь?',choices:[{text:'«Сначала уважение. Потом всё остальное.»',mod:10},{text:'«Главное — сила и страх.»',mod:-15},{text:'«Главное — держать слово перед своими.»',mod:15}]}
  };
  const RANKS=['Салага','Пацан','Блатной','Смотрящий','Авторитет','Вор в законе'];
  const REPKEY='avtoritet_npc_rep_v2',USEKEY='avtoritet_npc_uses_v2',INTKEY='avtoritet_npc_interactions_v2_';
  const COOLDOWN=30*60*1000,MAX_FREE=2,AD_BONUS=2;
  let rep={},uses={};
  try{rep=JSON.parse(localStorage.getItem(REPKEY)||'{}')||{}}catch(e){rep={}}
  try{uses=JSON.parse(localStorage.getItem(USEKEY)||'{}')||{}}catch(e){uses={}}
  const save=()=>{try{localStorage.setItem(REPKEY,JSON.stringify(rep));localStorage.setItem(USEKEY,JSON.stringify(uses))}catch(e){}};
  function readGame(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')||{}}catch(e){return {}}}
  function writeGame(s){try{s.saveUpdatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s));return true}catch(e){return false}}
  const getRep=id=>Math.max(0,Number(rep[id]||0));
  const rankIndex=()=>{const s=readGame(),p=Number(s.points||0);let i=0;const t=[0,100,500,2000,8000,25000];for(let j=0;j<t.length;j++)if(p>=t[j])i=j;return i};
  const unlocked=id=>rankIndex()>=NPCS[id].rank;
  const data=id=>{const x=uses[id]||{};return {used:Number(x.used||0),extra:Number(x.extra||0),until:Number(x.until||0)}};
  const level=id=>Math.floor(getRep(id)/3)+1;
  function state(id){const d=data(id),now=Date.now();if(d.until&&now>=d.until){d.used=0;d.extra=0;d.until=0;uses[id]=d;save()}const free=Math.max(0,MAX_FREE-d.used),extra=Math.max(0,d.extra);return {used:d.used,extra,free,total:free+extra,locked:d.until>now,until:d.until};}
  function clampChance(n){return Math.max(5,Math.min(95,Math.round(n)))}
  function cooldownText(until){const left=Math.max(0,until-Date.now()),m=Math.ceil(left/60000),sec=Math.ceil((left%60000)/1000);return m>1?m+' мин':sec+' сек'}
  function npcHero(id,n){return '<div class="npc-hero"><img class="npc-hero-img" src="'+n.avatar+'" alt="Аватар '+n.name+'" loading="eager"><div class="npc-hero-gradient"></div><div class="npc-hero-title"><span>'+n.icon+'</span><b>'+n.name+'</b><small>'+n.desc+'</small></div></div>'}
  function enterNpcModal(){const m=$('modal');if(m)m.classList.add('npc-modal')}
  function leaveNpcModal(){const m=$('modal');if(m)m.classList.remove('npc-modal')}
  function card(id,n){const st=state(id),r=getRep(id),lv=level(id),unavailable=!unlocked(id);let note='';if(unavailable)note='🔒 Откроется с мастью «'+RANKS[n.rank]+'»';else if(st.locked)note='⏳ Отдохни ещё '+cooldownText(st.until);else if(st.total<=0)note='🎬 Ещё 2 обращения можно получить за рекламу';else note='Осталось обращений: '+st.total;return '<button type="button" class="npc-btn npc-custom" data-custom-npc="'+id+'" style="text-align:left;padding:14px;margin-bottom:8px;width:100%;opacity:'+(unavailable?.55:1)+'">'+n.icon+' <b>'+n.name+'</b><br><small>'+n.desc+' · доверие '+r+' · уровень '+lv+'</small><br><span>▶ '+n.action+'</span><br><small>Награда: '+n.reward+'</small><br><small>'+note+'</small></button>'}
  function render(){leaveNpcModal();const c=$('modal-content');if(!c)return;const title=c.querySelector('h2');if(!title||!title.textContent.includes('Барак'))return;c.innerHTML='<h2>☰ Барак</h2><p>Свои не раздают доверие за просто так. У каждого — 2 обращения, потом перерыв 30 минут.</p><div>'+Object.entries(NPCS).map(([id,n])=>'<button type="button" class="npc-link" data-open-npc="'+id+'" style="width:100%;margin:5px 0;padding:11px;text-align:left">'+n.icon+' '+n.name+' — '+n.desc+'</button>').join('')+'</div><hr><h3>🏆 Достижения</h3><p>Тап-машина, Критический удар, Решала, Пачка за пачкой.</p><h3>💎 Новый срок</h3><p>После 25 000 ⭐ можно начать новый срок и сохранить постоянный бонус силы.</p><button type="button" id="prestige-custom" style="width:100%;padding:12px">Начать новый срок</button>';c.querySelectorAll('[data-open-npc]').forEach(b=>b.onclick=()=>openNpc(b.dataset.openNpc));const p=$('prestige-custom');if(p)p.onclick=()=>{if(typeof window.more==='function'){window.more();setTimeout(()=>{$('prestige')?.click()},20)}}}
  function openNpc(id){const n=NPCS[id];if(!n)return;if(!unlocked(id)){msgLocal('🔒 '+n.name+' пока не для твоей масти. Нужна масть «'+RANKS[n.rank]+'».');return}enterNpcModal();const c=$('modal-content');if(!c)return;c.innerHTML=npcHero(id,n)+'<div class="npc-action-panel"><h2>'+n.icon+' '+n.name+'</h2><div class="npc-dialogue"><b>'+n.name+':</b><p>'+n.dialogue+'</p></div><button type="button" class="npc-primary" id="npc-start">'+n.action+' →</button><button type="button" id="npc-back" style="width:100%;margin-top:8px">Вернуться к бараку</button></div>';const start=$('npc-start');if(start)start.onclick=()=>startDialogue(id);const back=$('npc-back');if(back)back.onclick=()=>render()}
  function startDialogue(id){const n=NPCS[id],st=state(id);if(st.locked){msgLocal('⏳ '+n.name+' отшил тебя. Ещё '+cooldownText(st.until)+'.');return}if(st.total<=0){offerAd(id);return}const c=$('modal-content');if(!c)return;enterNpcModal();c.innerHTML=npcHero(id,n)+'<div class="npc-action-panel"><div class="npc-dialogue npc-question"><span class="npc-dialogue-label">'+n.name+'</span><p>'+n.dialogue+'</p></div><div class="npc-choice-title">Твой ответ повлияет на шанс успеха:</div><div class="npc-choices">'+n.choices.map((x,i)=>'<button type="button" class="npc-choice" data-choice="'+i+'">'+x.text+'<small>Шанс: '+clampChance(n.baseChance+x.mod)+'%</small></button>').join('')+'</div><button type="button" id="npc-back" style="width:100%;margin-top:8px">Назад</button></div>';c.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>chooseNpc(id,Number(b.dataset.choice)));const back=$('npc-back');if(back)back.onclick=()=>openNpc(id)}
  function chooseNpc(id,index){const n=NPCS[id],choice=n.choices[index];if(!choice)return;const chance=clampChance(n.baseChance+choice.mod);const c=$('modal-content');if(!c)return;c.innerHTML=npcHero(id,n)+'<div class="npc-action-panel"><div class="npc-dialogue"><span class="npc-dialogue-label">'+n.name+'</span><p>Хороший ответ. По твоему решению шанс успеха теперь <b>'+chance+'%</b>.</p></div><div class="npc-confirm-chance"><b>'+chance+'%</b><span>шанс успеха</span></div><button type="button" class="npc-primary" id="npc-confirm">Продолжить</button><button type="button" id="npc-change" style="width:100%;margin-top:8px">Изменить ответ</button></div>';const confirm=$('npc-confirm');if(confirm)confirm.onclick=()=>consumeAndRun(id,chance);const change=$('npc-change');if(change)change.onclick=()=>startDialogue(id)}
  function consumeAndRun(id,chance){const n=NPCS[id],st=state(id);if(st.total<=0){offerAd(id);return}const d=data(id);if(d.used<MAX_FREE)d.used++;else if(d.extra>0)d.extra--;if(d.used>=MAX_FREE&&d.extra<=0)d.until=Date.now()+COOLDOWN;uses[id]=d;save();const success=Math.random()*100<chance;const result=runNpcAction(id,success);if(typeof window.ui==='function')window.ui();const key=INTKEY+id;let count=0;try{count=Number(localStorage.getItem(key)||'0')+1;localStorage.setItem(key,String(count))}catch(e){count=1}let finalResult=result;if(count%3===0){rep[id]=getRep(id)+1;save();finalResult+=' · 🤝 Доверие выросло: '+rep[id]}showNpcResult(id,finalResult,success,chance)}
  function showNpcResult(id,text,success,chance){const n=NPCS[id],c=$('modal-content');if(!c)return;enterNpcModal();const st=state(id);c.innerHTML=npcHero(id,n)+'<div class="npc-action-panel"><div class="npc-result '+(success?'npc-success':'npc-fail')+'"><div class="npc-result-icon">'+(success?'✅':'❌')+'</div><div class="npc-result-chance">Шанс был <b>'+chance+'%</b></div><p><b>'+text+'</b></p><small>Осталось обращений: '+st.total+'</small></div><button type="button" class="npc-primary" id="npc-again">Ещё раз поговорить</button><button type="button" id="npc-back" style="width:100%;margin-top:8px">Вернуться к бараку</button></div>';const again=$('npc-again');if(again)again.onclick=()=>openNpc(id);const back=$('npc-back');if(back)back.onclick=()=>render()}
  function runNpcAction(id,success){const s=readGame();if(!s||s.jailed)return '🔒 Сначала выйди из карцера';if(id==='шайба'){if(!success)return '🧢 Шайба: дело сорвалось. Без прибыли, но и без потерь.';const gain=25+Number(s.prestige||0)*5;s.cigarettes=Number(s.cigarettes||0)+gain;s.respect=Number(s.respect||0)+1;writeGame(s);return '🧢 Шайба помог: +'+gain+' 🚬 и +1 🧠'}if(id==='бугор'){if(Number(s.energy||0)<10)return '⚡ Бугор: сначала восстанови хотя бы 10 энергии';if(!success)return '💪 Бугор: сегодня не твой день. Тренировка прошла впустую.';if(Number(s.energy||0)>=Number(s.maxEnergy||250))s.lastEnergyTime=Date.now();s.energy=Number(s.energy||0)-10;s.power=Number(s.power||1)+1;s.respect=Number(s.respect||0)+2;s.points=Number(s.points||0)+15;writeGame(s);return '💪 Бугор потренировал тебя: +1 💪 +2 🧠 +15 ⭐'}if(id==='косой'){if(success){s.cigarettes=Number(s.cigarettes||0)+100;s.points=Number(s.points||0)+40;writeGame(s);return '😏 Косой: сделка удалась! +100 🚬 +40 ⭐'}s.cigarettes=Math.max(0,Number(s.cigarettes||0)-60);s.points=Math.max(0,Number(s.points||0)-20);writeGame(s);return '😏 Косой: сделка провалилась. -60 🚬 -20 ⭐'}if(id==='смотрящий'){if(!success)return '👑 Смотрящий: совет не сработал. Возвращайся, когда будешь готов слушать внимательнее.';const p=Number(s.points||0);let i=0;const t=[0,100,500,2000,8000,25000];for(let j=0;j<t.length;j++)if(p>=t[j])i=j;const next=t.find(x=>x>p)||t[t.length-1];return '👑 Смотрящий: твой текущий уровень — «'+RANKS[i]+'». Следующая цель: '+next+' ⭐'}return '🤝 Разговор закончен.'}
  function offerAd(id){const n=NPCS[id],c=$('modal-content');if(!c)return;enterNpcModal();c.innerHTML=npcHero(id,n)+'<div class="npc-action-panel"><h2>🎬 Ещё два дела</h2><p>'+n.icon+' '+n.name+' сейчас недоступен.</p><p>Посмотри рекламу и получи ещё <b>2 обращения</b> к '+n.name+'.</p><button type="button" id="npc-ad" style="width:100%;padding:13px">🎬 Посмотреть рекламу → +2 обращения</button><button type="button" id="npc-ad-back" style="width:100%;margin-top:7px">Вернуться к разговору</button></div>';$('npc-ad').onclick=()=>{if(typeof window.showRewardedAd==='function')window.showRewardedAd(rewarded=>{if(rewarded===false){msgLocal('📺 Награда не получена. Попробуй позже.');return}grantAd(id)});else msgLocal('📺 Реклама пока не подключена.')};$('npc-ad-back').onclick=()=>openNpc(id)}
  function grantAd(id){const d=data(id);d.extra=(d.extra||0)+AD_BONUS;uses[id]=d;save();showNpcResult(id,'🎁 '+NPCS[id].name+': +2 обращения получены за рекламу.',true,100)}
  function msgLocal(x){if(typeof window.msg==='function')window.msg(x);else alert(x)}
  function init(){document.addEventListener('click',e=>{if(e.target.closest('#btn-more'))setTimeout(render,20);if(e.target.closest('#modal-close'))setTimeout(leaveNpcModal,0)})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();